name: shared
description: CÃ³digo compartido entre las apps QuickBite
version: 1.0.0
publish_to: 'none'

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  http: ^1.1.0
  dio: ^5.4.0
  intl: ^0.19.0
